version: '3.8'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["bundle", "exec", "rails", "server"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
