default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: mysecretpassword
  database: postgres


development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: mysecretpassword
  database: postgres
